"""The Vorquel Brain V1 contract: vocabularies, schemas and the rules between them.

This package is the machine-readable form of the Brain V1 contract. It defines
*what* a Brain object is and *what makes one invalid*. It deliberately does not
store, retrieve, assemble or serve anything — the schemas are the durable
artifact and the validators are pure functions over them.

Scope of Brain-V1-A, stated here so the boundary is visible from the entry
point: no live migration, no storage, no retrieval engine, no ContextPack
generator, no MCP server. Those belong to later work.

The four reconciliation decisions recorded in
``docs/BRAIN_CONTRACT_V1_RECONCILIATION.md`` are encoded in :mod:`.enums` rather
than described, so that tests assert them instead of readers trusting prose.
"""

from __future__ import annotations

from .enums import (
    BRAIN_V1_CONTROLLED_WRITES,
    BRAIN_V1_READS,
    BRAIN_V1_TOOLS,
    CANDIDATE_STATUSES,
    CANDIDATE_TYPES,
    CLAIM_STATUSES,
    CONTEXT_PACK_MODES,
    CONTRACT_VERSION,
    DATA_CLASSES,
    DECISION_STATUSES,
    ENTITY_TYPES,
    EPISTEMIC_STATUS_DISPLAY,
    EPISTEMIC_STATUSES,
    EPISTEMIC_STATUSES_REQUIRING_PROVENANCE,
    EVENT_TYPES,
    EVIDENCE_DIRECTIONS,
    EVIDENCE_TYPES,
    FORBIDDEN_EPISTEMIC_PROMOTIONS,
    FORBIDDEN_FIELD_NAMES,
    FRAGMENT_TYPES,
    FRESHNESS_STATUSES,
    HYPOTHESIS_STATUSES,
    HYPOTHESIS_STATUSES_REQUIRING_NEXT_LEARNING,
    INSTRUCTION_AUTHORITIES,
    LEGACY_STORAGE_SCOPE_TYPES,
    LOCATOR_KINDS,
    NO_EVIDENCE_FOUND,
    SCOPE_TYPES,
    SCOPES_AWAITING_STORAGE_MIGRATION,
    SENSITIVITY_FORBIDDEN_IN_CONTEXT_PACK,
    SENSITIVITY_LEVELS,
    SOURCE_TYPES,
    TRUST_CLASSES,
    UNKNOWN_PRIORITIES,
    UNKNOWN_STATUSES,
    VERIFICATION_STATES,
    display_epistemic_status,
)
from .registry import (
    V1_OBJECTS,
    is_structurally_valid,
    load_all_schemas,
    schema_for,
    structural_errors,
)
from .validators import (
    CRITICAL,
    ERROR,
    ValidationReport,
    Violation,
    check_active_decisions_in_projection,
    check_candidate_is_not_canonical,
    check_context_pack_excludes_secret,
    check_context_pack_provenance,
    check_decision_supersession,
    check_epistemic_promotion,
    check_epistemic_provenance,
    check_evidence_supports_claim_scope,
    check_gaps_are_not_findings,
    check_no_evidence_not_false,
    check_no_forbidden_fields,
    check_pii_orthogonality,
    check_scope_isolation,
    validate_graph,
)

__all__ = [
    "BRAIN_V1_CONTROLLED_WRITES",
    "BRAIN_V1_READS",
    "BRAIN_V1_TOOLS",
    "CANDIDATE_STATUSES",
    "CANDIDATE_TYPES",
    "CLAIM_STATUSES",
    "CONTEXT_PACK_MODES",
    "CONTRACT_VERSION",
    "CRITICAL",
    "DATA_CLASSES",
    "DECISION_STATUSES",
    "ENTITY_TYPES",
    "EPISTEMIC_STATUSES",
    "EPISTEMIC_STATUSES_REQUIRING_PROVENANCE",
    "EPISTEMIC_STATUS_DISPLAY",
    "ERROR",
    "EVENT_TYPES",
    "EVIDENCE_DIRECTIONS",
    "EVIDENCE_TYPES",
    "FORBIDDEN_EPISTEMIC_PROMOTIONS",
    "FORBIDDEN_FIELD_NAMES",
    "FRAGMENT_TYPES",
    "FRESHNESS_STATUSES",
    "HYPOTHESIS_STATUSES",
    "HYPOTHESIS_STATUSES_REQUIRING_NEXT_LEARNING",
    "INSTRUCTION_AUTHORITIES",
    "LEGACY_STORAGE_SCOPE_TYPES",
    "LOCATOR_KINDS",
    "NO_EVIDENCE_FOUND",
    "SCOPES_AWAITING_STORAGE_MIGRATION",
    "SCOPE_TYPES",
    "SENSITIVITY_FORBIDDEN_IN_CONTEXT_PACK",
    "SENSITIVITY_LEVELS",
    "SOURCE_TYPES",
    "TRUST_CLASSES",
    "UNKNOWN_PRIORITIES",
    "UNKNOWN_STATUSES",
    "V1_OBJECTS",
    "VERIFICATION_STATES",
    "ValidationReport",
    "Violation",
    "check_active_decisions_in_projection",
    "check_candidate_is_not_canonical",
    "check_context_pack_excludes_secret",
    "check_context_pack_provenance",
    "check_decision_supersession",
    "check_epistemic_promotion",
    "check_epistemic_provenance",
    "check_evidence_supports_claim_scope",
    "check_gaps_are_not_findings",
    "check_no_evidence_not_false",
    "check_no_forbidden_fields",
    "check_pii_orthogonality",
    "check_scope_isolation",
    "display_epistemic_status",
    "is_structurally_valid",
    "load_all_schemas",
    "schema_for",
    "structural_errors",
    "validate_graph",
]
